name       : kmod
version    : '30'
release    : 12
source     :
    - https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-30.tar.xz : f897dd72698dc6ac1ef03255cd0a5734ad932318e4adbaebc7338ef2f5202f9f
component  : system.base
license    :
    - LGPL-2.1-or-later # for libkmod, testsuite and helper libraries
    - GPL-2.0-or-later  # for tools
summary    : Linux kernel module management utilities
description: |
    Linux kernel module management utilities
builddeps  :
    - pkgconfig(libzstd)
optimize   :
    - lto
    - size
setup      : |
    %patch -p1 < $pkgfiles/0001-libkmod-Support-usr-lib-to-enable-stateless-configs-.patch
    %configure --bindir=/bin       \
               --with-xz           \
               --with-zlib         \
               --with-zstd
build      : |
    %make
install    : |
    %make_install
    mkdir $installdir/sbin
    for target in modprobe modinfo rmmod insmod depmod lsmod ; do
        ln -sv /bin/kmod $installdir/sbin/${target}
    done
