name       : kmod
version    : '25'
release    : 11
source     :
    - https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-25.tar.xz : 7165e6496656159dcb909a91ed708a0fe273a4b128b4b1dc997ccb5189eef1cd
component  : system.base
license    :
    - LGPL-2.1 # for libkmod, testsuite and helper libraries
    - GPL-2.0  # for tools
summary    : Linux kernel module management utilities
description: |
    Linux kernel module management utilities
optimize   :
    - lto
    - size
setup      : |
    %patch -p1 < $pkgfiles/0001-libkmod-Support-usr-lib-to-enable-stateless-configs-.patch
    %configure --bindir=/bin       \
               --disable-manpages  \
               --with-xz           \
               --with-zlib
build      : |
    %make
install    : |
    %make_install
    mkdir $installdir/sbin
    for target in modprobe modinfo rmmod insmod depmod lsmod ; do
        ln -sv /bin/kmod $installdir/sbin/${target}
    done
